---
api:
  admins:
    - 'admin@domain.com'
  database_uri: 'mysql+pymysql://oemf:oemf@localhost:3306/oemf'
  env: 'development'
  host: 127.0.0.1
  log_level: INFO
  secret_key: 'somesecretormaybenot'
  sqlalchemy:
    echo: false
    track_modifications: false
  jwt:
    issuer: localhost
    secret: 'anothersecretmaybenot'
    lifetime: 600
    algorithm: 'HS256'
