FROM node:22 AS builder

RUN set -eux; \
  apt-get update; \
  DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; \
  rm -rf /var/lib/apt/lists/*; \
  apt-get clean

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN npm config set proxy ${HTTP_PROXY} && \
  npm config set https-proxy ${HTTPS_PROXY} && \
  npm install -g npm@11.4.1 && \
  npm install -g @angular/cli@19

COPY frontend/src src
COPY frontend/angular.json angular.json
COPY frontend/package-lock.json package-lock.json
COPY frontend/package.json package.json
COPY frontend/tsconfig.app.json tsconfig.app.json
COPY frontend/tsconfig.json tsconfig.json
COPY frontend/tsconfig.spec.json tsconfig.spec.json

RUN npm cache clear --force && \
  npm install && \
  ng build --configuration production

FROM nginx:1.28.0

RUN set -eux; \
  apt-get update; \
  DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; \
  rm -rf /var/lib/apt/lists/*; \
  apt-get clean

ENV API_URL="http://localhost:5000/api"

RUN chown -R nginx:nginx /var/cache/nginx && \
  chown -R nginx:nginx /var/log/nginx && \
  chown -R nginx:nginx /etc/nginx/conf.d && \
  chown -R nginx:nginx /docker-entrypoint.d/ && \
  chmod -R 777 /etc/nginx/conf.d && \
  rm /etc/nginx/conf.d/default.conf && \
  touch /run/nginx.pid && \
  chown -R nginx:nginx /run/nginx.pid

COPY docker/frontend-settings.sh /docker-entrypoint.d/frontend-settings.sh
RUN chmod 775 /docker-entrypoint.d/frontend-settings.sh && \
  chown nginx:nginx /docker-entrypoint.d/frontend-settings.sh

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/dist/frontend/browser /usr/share/nginx/html
RUN chown -R nginx:nginx /usr/share/nginx/html

USER nginx

ENV TZ="Europe/Paris"

EXPOSE 4200
CMD ["nginx","-g","daemon off;"]
