"""Init db.

Revision ID: 01c5b9be3180
Revises:
Create Date: 2025-02-07 15:33:05.079076

"""

# Copyright (c) 2025 oemf.jrmv.net

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "01c5b9be3180"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade db."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("club", sa.String(length=255), nullable=False),
        sa.Column("encrypted_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "arrows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("found", "lost", name="arrowaction"),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("shaft_manufacturer", sa.String(length=255), nullable=True),
        sa.Column("shaft_model", sa.String(length=255), nullable=True),
        sa.Column("shaft_material", sa.String(length=255), nullable=True),
        sa.Column("shaft_color", sa.String(length=255), nullable=True),
        sa.Column("shaft_length", sa.Float(), nullable=True),
        sa.Column("vanes_count", sa.Integer(), nullable=False),
        sa.Column("vanes_color", sa.String(length=255), nullable=True),
        sa.Column("point", sa.String(length=255), nullable=True),
        sa.Column("nock", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade db."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("arrows")
    op.drop_table("users")
    # ### end Alembic commands ###
