"""Init db

Revision ID: abc4ed5bd6ce
Revises:
Create Date: 2024-11-01 16:37:54.929300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc4ed5bd6ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'addresses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('street', sa.String(), nullable=False),
        sa.Column('city', sa.String(), nullable=False),
        sa.Column('postal_code', sa.String(), nullable=False),
        sa.Column('country', sa.String(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'shafts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('manufacturer', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('material', sa.String(), nullable=True),
        sa.Column('color', sa.String(), nullable=True),
        sa.Column('length', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('club', sa.String(), nullable=False),
        sa.Column('encrypted_password', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'vanes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('manufacturer', sa.String(), nullable=True),
        sa.Column('color', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'places',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('address_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'arrows',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'action',
            sa.Enum('found', 'search', name='arrowaction'),
            nullable=False,
        ),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('shaft_id', sa.Integer(), nullable=True),
        sa.Column('place_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
        sa.ForeignKeyConstraint(['shaft_id'], ['shafts.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'arrow_vanes',
        sa.Column('arrow_id', sa.Integer(), nullable=False),
        sa.Column('vane_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['arrow_id'],
            ['arrows.id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['vane_id'], ['vanes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('arrow_id', 'vane_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrow_vanes')
    op.drop_table('arrows')
    op.drop_table('places')
    op.drop_table('vanes')
    op.drop_table('users')
    op.drop_table('shafts')
    op.drop_table('addresses')
    # ### end Alembic commands ###
